---
output: html_fragment
---

```{r setup_cluster, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = F, message = F,results='asis')
```


```{r,}
#
suppressPackageStartupMessages(library(dave.help))

htmltools::tagList(rmarkdown::html_dependency_font_awesome()) # required for icons



```

```{r}
#DAVe Cluster
#-------------
module<-'Cluster'
link_name<-main_link_name<-'dave.cluster'

section_name<-NULL
section_links<-inner_link(paste0(link_name,section_name))$anchor %>% cat()

.path<-function(path,relative='../../'){
  paste0(relative, path)
}
path<-.path('img/dave.cluster/')

fig_right<-TRUE
mod_description<-'This module is used to identified clusters of related groups of samples and variables.'

link_name<-'dave.cluster'
section_name<-NULL
inner_link(paste0(link_name,section_name))$anchor %>% cat()

args_main<-list(title=module,
    nav=paste0(path,'nav.png'),
    mod_desc=as.character(mod_description),
    section=NULL,
    collapse='\n<br>\n',section_tags='')

link_name<-'dave.cluster.'
section_links<-create_links(link_name)

HCA_description<-'This module is used to carry out hierarchical cluster analysis (HCA) on samples and variables. HCA distance and agglomeration methods can be used to organize the input based on similarity and identify clusters of closely related samples or variables based on the raw data or correlations.'
#calculate menue
#------------------------------
# section_name<-'.cluster'
# inner_link(paste0(link_name,section_name))$anchor %>% cat()

methods<-list(text='Use the <code>nodes</code> menue to specify if samples or variables will be clustered. You can additionally specify <code>names</code> used for labels and <code>annotations</code> used for displaying group metadata.',
              fig= paste0(path,'nodes.png'),
              fig_right=fig_right,4)

methods2<-list(text='The <code>methods</code> menue is used to optionally specify a correlation method, set HCA distance and linkage methods and select the number of clusters.',
              fig= paste0(path,'methods.png'),
              fig_right=fig_right,4)

methods<-list(methods,methods2)

#results
#-------
# section_name<-'.results'
# inner_link(paste0(link_name,section_name))$anchor %>% cat()
results<-list(list(text=NULL,#'Overview methods and clustering results.',
              fig= paste0(path,'results.png'),
              fig_right=fig_right,4))
#plots
#-----
# section_name<-'.plots'
# inner_link(paste0(link_name,section_name))$anchor %>% cat()
plots<-list(
            list(text='Select <code>dendrogram</code> plot type to focus on the relationship between HCA ordering and metadata set in the <code>node</code> >> <code>annotations</code> menue.',
              fig= paste0(path,'dendrogram_explore.png'),
              fig_right=fig_right,4),
            list(text='Select <code>explore</code> and <code>heatmap</code> plot type to overveiw sample and/or variable similarities and groups.',
              fig= paste0(path,'heatmap_explore.png'),
              fig_right=fig_right,4),
            list(text='Click and drag the mouse on the heat map to zoom in.',
              fig= paste0(path,'heatmap_explore_zoom.png'),
              fig_right=fig_right,4),
            list(text='Use <code>plot</code> >> <code>heatmap</code> to visualize heatmap and metadata.',
              fig= paste0(path,'heatmap_plot.png'),
              fig_right=fig_right,4)
            )

args_HCA<-list(title=NULL,
    nav=NULL,
    mod_desc=NULL,
    section=list(
      list(section='link',asis=TRUE ,content=section_links$methods),
      list(section=section_title('Methods') ,content=methods),
      list(section='link',asis=TRUE ,content=section_links$results),
      list(section=section_title('Results') ,content=results),
      list(section='link',asis=TRUE ,content=section_links$plots),
      list(section=section_title('Explore and Plot') ,content=plots),
      list(section='link',asis=TRUE ,content=section_links$results)),
    collapse='\n<br>\n',section_tags='h3')


#combine all args
#------------------
multi_args<-list(
  list(title=NULL ,
       description=NULL,
       args=args_main),
  list(title=submodule_title('Hierarchical cluster analysis (HCA)') ,
       description=HCA_description,
       args=args_HCA))

out<-lapply(1:length(multi_args),function(i){
  title<-multi_args[[i]]$title
  content<-do.call('render_skeleton', multi_args[[i]]$args) 
  c(title,multi_args[[i]]$description,content)
}) %>% 
  unlist() %>%
  paste0(.,collapse = '\n<br>\n') 

out %>% HTML()

#do.call('render_skeleton', args) %>% HTML()
```

