---
output: html_fragment
---

```{r setup_data, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = F, message = F,results='asis')
```


```{r}
#
suppressPackageStartupMessages(library(dave.help))

htmltools::tagList(rmarkdown::html_dependency_font_awesome()) # required for icons

```

<!-- ## `r dcr_g('Data reference')` -->

```{r}
#DAVe preprocess
#-------------
module<-'Data reference'
link_name<-main_link_name<-'dave.reference.api'

section_name<-NULL
section_links<-inner_link(paste0(link_name,section_name))$anchor %>% cat()

.path<-function(path,relative='../../'){
  paste0(relative, path)
}

path<-.path('img/dave.main/')
mod_description<-'This module is used to overview and manage data and metadata objects.'


args_main<-list(title=NULL,
    nav=paste0(path,'nav.png'),
    mod_desc=as.character(mod_description),
    section=NULL,
    collapse='\n<br>\n',section_tags='')

data_description<-'To get started format your data into two parts as shown below and then follow allong with the instructions in <code>preprocess</code> >> <code>merge</code> to create an analysis ready data object.'


#calculate menue
#------------------------------
# section_name<-'.methods'
# inner_link(paste0(link_name,section_name))$anchor %>% cat()
methods<-list(list(text="The data should be formated into two parts 1) the main data containing sample descriptions and numeric variable data and 2) variable meta data.",
                fig= paste0(path,'data_diagram1.png'),
                fig_right=FALSE,4),
              list(text="The main components include the ability to select and view the data.",
                fig= paste0(path,'select.png'),
                fig_right=FALSE,4),
              list(text="Selected data is shown in the overview.",
                fig= paste0(path,'overview.png'),
                fig_right=FALSE,4),
              list(text="Data can be uploaded in the following formats: .csv, project or example.",
                fig= paste0(path,'load.png'),
                fig_right=FALSE,4),
              list(text="Data can be saved as a .csv for download or a project which can be loaded later.",
                fig= paste0(path,'save.png'),
                fig_right=FALSE,4),
              list(text="Deletion of data objects can be done here.",
                fig= paste0(path,'delete.png'),
                fig_right=FALSE,4)
              )

args_data<-list(title=NULL,
    nav=NULL,
    mod_desc=NULL,
    section=list(
      list(section='link',asis=TRUE ,content=section_links$methods),
      list(section=section_title('Methods') ,content=methods)),
    collapse='\n<br>\n',section_tags='')


#combine all args
#------------------
multi_args<-list(
  list(title=NULL ,
       description=NULL,
       args=args_main),
  list(title=submodule_title('Data management') ,
       description=data_description,
       args=args_data))

out<-lapply(1:length(multi_args),function(i){
  title<-multi_args[[i]]$title
  content<-do.call('render_skeleton', multi_args[[i]]$args) 
  c(title,multi_args[[i]]$description,content)
}) %>% 
  unlist() %>%
  paste0(.,collapse = '\n<br>\n') 

out %>% HTML()
```

