---
output: html_fragment
---


```{r,echo=FALSE,message=FALSE,warning=FALSE}
library(dave.help)

htmltools::tagList(rmarkdown::html_dependency_font_awesome()) # required for icons

#custom CSS
includeCSS(system.file('www/css/styles.css',package="dave.help"))


```


```{r,echo = FALSE, warning = F, message = F,results='asis'}
#DAVe preprocess
#-------------
module<-'Data Preprocessing reference'
link_name<-main_link_name<-'dave.preproc.api'

section_name<-NULL
inner_link(paste0(link_name,section_name))$anchor %>% cat()

.path<-function(path,relative='../../'){
  paste0(relative, path)
}


path<-.path('img/dave.preproc/')
mod_description<-'This  module is used to merge, filter and prepare the data for analysis.'
fig_right<-TRUE


#main preproc menue
args_main<-list(title=NULL,
    nav=paste0(path,'nav.png'),
    mod_desc=as.character(mod_description),
    section=NULL,
    collapse='\n<br>\n',section_tags='')

#----------
# Merge
#----------

#calculate menue
merge_description<-'<code>Merge</code> is used to identify experimental design factors and merge numeric and variable metadata.'

link_name<-paste0(main_link_name,'.merge.')
section_links<-create_links(link_name)

# section_name<-'.methods'
# inner_link(paste0(link_name,section_name))$anchor %>% cat()
methods<-list(
              list(text="Select sample meta data (e.g. non-numeric descriptors of the experimental design) which will be added to the <code>_row_meta</code> object and made available to use in visual mapping and analysis/calculation controls.",
                fig= paste0(path,'data_diagram2.png'),
                fig_right=fig_right,4),
              list(text="Identify and row meta data.",
                fig= paste0(path,'preproc_merge_samples.png'),
                fig_right=fig_right,4),
              list(text="Identify and add column or measurement meta data, wherein ID sets the unique row identifier (e.g. row number).",
                fig= paste0(path,'preproc_merge_variables.png'),
                fig_right=fig_right,4)
              )


#results
#-------
# section_name<-'.results'
# inner_link(paste0(link_name,section_name))$anchor %>% cat()
results<-list(list(text=NULL,#'Overview the merge results.',
              fig= paste0(path,'preproc_merge_results.png'),
              fig_right=fig_right,4))
#plots
#-----
# section_name<-'.plots'
# inner_link(paste0(link_name,section_name))$anchor %>% cat()
plots<-list(
            list(text="Visualize a summary of the merged data.",
              fig= paste0(path,'preproc_merge_plot.png'),
              fig_right=fig_right,4)
            )

 
# section_name<-'.save'
# inner_link(paste0(link_name,section_name))$anchor %>% cat()
save<-list(
            list(text="Use <code>save</code> to create a data set which will be used for further analyses.",
              fig= paste0(path,'preproc_save.png'),
              fig_right=fig_right,4))


#merge menue
args_merge<-list(title=NULL,
    nav=NULL,
    mod_desc=NULL,
    section=list(
      list(section='link',asis=TRUE ,content=section_links$methods),
      list(section=section_title('Methods') ,content=methods),
      list(section='link',asis=TRUE ,content=section_links$results),
      list(section=section_title('Results') ,content=results),
      list(section='link',asis=TRUE ,content=section_links$plots),
      list(section=section_title('Explore and Plot') ,content=plots),
      list(section='link',asis=TRUE ,content=section_links$report),
      list(section='link',asis=TRUE ,content=section_links$save),
      list(section=section_title('Save') ,content=save)),
    collapse='\n<br>\n',section_tags='h3')


#filter menue
#---------------
filter_description<-'<code>Filter</code> can be used to identify and remove variables with missing values. Specify a factor <code>group</code> of interest and the <code>missing cutoff</code> or percent acceptible missing for each level in the <code>group</code>. It is also useful to remove non-informative varibles or those with a standard deviation of zero (<code>remove zero variance</code>).' 

link_name<-'dave.preproc.filter.'
section_links<-create_links(link_name)
# section_name<-'.methods'
# inner_link(paste0(link_name,section_name))$anchor %>% cat()


methods<-list(
              list(text="Remove error prone variables with too many missing values or zero variance.",
                fig= paste0(path,'preproc_missing.png'),
                fig_right=fig_right,4),
              list(text="Optionaly select groups of samples to evaluate missing values.",
                fig= paste0(path,'preproc_missing_filter.png'),
                fig_right=fig_right,4),
              list(text="Impute all missing values in the data. Replace based on a variery of sumaries based on the presnt values.",
                fig= paste0(path,'preproc_missing_impute1.png'),
                fig_right=fig_right,4)
              )


#results
#-------
# section_name<-'.results'
# inner_link(paste0(link_name,section_name))$anchor %>% cat()

results<-list(list(text=NULL,#'Overview the filter results.',
              fig= paste0(path,'preproc_missing_results.png'),
              fig_right=fig_right,4))
#plots
#-----
# section_name<-'.plots'
# inner_link(paste0(link_name,section_name))$anchor %>% cat()

plots<-list(
            list(text="View missing data for each sample and variable, overall and by class. Missing or zero variables shown in red are arranged based on their sample (row) and variable (column) number.",
              fig= paste0(path,'preproc_missing_plot1.png'),
              fig_right=fig_right,4),
            list(text="Flagged variables, or those containing greater or equal percent zero or missing values than the <code>missing cutoff</code> are shown in red for each level of a group <code>group</code>.",
              fig= paste0(path,'preproc_missing_plot2.png'),
              fig_right=fig_right,4)
            )

# #create report
# merge_report<-report_collapse(path=system.file(package='dave.help','reports/model_report.html'),title='Report',icon="file") %>% as.character() #%>% HTML()
# #add custom message
# icon<-'file'
# title<-'Report'
# message<-paste0('<h4>Click ',
#                 tags$label(
#                            HTML(paste0('<i class="fa fa-',icon,'"></i>')), title) %>% as.character(),
#                 ' below to collapse the example.</h4>')
# report_alert<-make_alert(message=message,color='#377eb8') %>% as.character()
# merge_report<-paste(report_alert,merge_report,collapse='\n')

#merge menu
args_filter<-list(title=NULL,
    nav=NULL,
    mod_desc=NULL,
    section=list(
      list(section='link',asis=TRUE ,content=section_links$methods),
      list(section=section_title('Methods') ,content=methods),
      list(section='link',asis=TRUE ,content=section_links$results),
      list(section=section_title('Results') ,content=results),
      list(section='link',asis=TRUE ,content=section_links$plots),
      list(section=section_title('Explore and Plot') ,content=plots),
      list(section='link',asis=TRUE ,content=section_links$report),
      # list(section='report',asis=TRUE ,content=merge_report),
      list(section='link',asis=TRUE ,content=section_links$save)),
    collapse='\n<br>\n',section_tags='h3')


#combine all args
#------------------
multi_args<-list(
  list(title=NULL ,
       description=NULL,
       args=args_main),
  list(title=submodule_title('Merge') ,
       description=merge_description,
       args=args_merge),
  list(title=submodule_title('Filter'),
       description=filter_description,
       args=args_filter))

out<-lapply(1:length(multi_args),function(i){
  title<-multi_args[[i]]$title
  content<-do.call('render_skeleton', multi_args[[i]]$args) 
  c(title,multi_args[[i]]$description,content)
}) %>% 
  unlist() %>%
  paste0(.,collapse = '\n<br>\n') 

out %>% HTML()

```

