---
output: html_fragment
---

```{r setup_stats, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = F, message = F,results='asis')
```


```{r}
#
suppressPackageStartupMessages(library(dave.help))

htmltools::tagList(rmarkdown::html_dependency_font_awesome()) # required for icons



```

<!-- Statistics -->
```{r}
#DAVe Statistics
#-------------
module<-'Statistics'
link_name<-main_link_name<-'dave.statistics'

section_name<-NULL
section_links<-inner_link(paste0(link_name,section_name))$anchor %>% cat()

.path<-function(path,relative='../../'){
  paste0(relative, path)
}

path<-.path('img/dave.stat/')


mod_description<-'This module is used to carry out statistical analyses, identify and filter the data based on significant differential expression.'


args_main<-list(title=module,
    nav=paste0(path,'nav.png'),
    mod_desc=as.character(mod_description),
    section=NULL,
    collapse='\n<br>\n',section_tags='')

link_name<-'dave.statistics.'
section_links<-create_links(link_name)

KS_description<-'This is a non-parametric test for differences in means between two groups. This test does not assume normality and can be robust to outliers when testing for differences in means between two groups with small samples sizes. This module can also be used to identify differentially expressed variables between groups and create filtered datasets based on the test p-values.'

#calculate menue
#------------------------------
# section_name<-'.methods'
# inner_link(paste0(link_name,section_name))$anchor %>% cat()
methods<-list(list(text="Identify experimental design factor(s) to use for tests and specify variable meta data.",
                fig= paste0(path,'design.png'),
                fig_right=FALSE,4),
              list(text="Select significance level (alpha) to use in visualizations and filter the data.",
                fig= paste0(path,'filter.png'),
                fig_right=FALSE,4)
              )


#results
#-------
# section_name<-'.results'
# inner_link(paste0(link_name,section_name))$anchor %>% cat()
results<-list(list(text=NULL,#'Overview methods and statistical analysis results.',
              fig= paste0(path,'results.png'),
              fig_right=FALSE,4))
#plots
#-----
# section_name<-'.plots'
# inner_link(paste0(link_name,section_name))$anchor %>% cat()
plots<-list(
            list(text='Create a volcano plot to visualize the relationship between variable fold-changes between groups and test p-values.',
              fig= paste0(path,'volcanoe.png'),
              fig_right=FALSE,4),
            list(text='Identify variables with large fold-changes between groups and low p-values.',
              fig= paste0(path,'volcanoe_explore.png'),
              fig_right=FALSE,4),
            list(text='Select one or many variables to generate violin density plots.',
              fig= paste0(path,'violin.png'),
              fig_right=FALSE,4),
             list(text='Explore variable distributions among groups.',
              fig= paste0(path,'violin_explore.png'),
              fig_right=FALSE,4),
            list(text='Use <code>plot</code> to view many variables and overview the plot style for the <code>report</code>.',
              fig= paste0(path,'violin_plot.png'),
              fig_right=FALSE,4)
            )


text<-"Explore variable distributions among groups."
fig<-"img/dave.stat/violin_explore.png"


# section_name<-'.save'
# inner_link(paste0(link_name,section_name))$anchor %>% cat()
save<-list(
            list(text='Save results and optionally remove non-significant variables by selecting <code>keep selected</code>.',
              fig= paste0(path,'save.png'),
              fig_right=FALSE,4))

args_KS<-list(title=NULL,
    nav=NULL,
    mod_desc=NULL,
    section=list(
      list(section='link',asis=TRUE ,content=section_links$methods),
      list(section=section_title('Methods') ,content=methods),
      list(section='link',asis=TRUE ,content=section_links$results),
      list(section=section_title('Results') ,content=results),
      list(section='link',asis=TRUE ,content=section_links$plots),
      list(section=section_title('Explore and Plot') ,content=plots),
      list(section='link',asis=TRUE ,content=section_links$results),
      list(section='link',asis=TRUE ,content=section_links$save),
      list(section=section_title('Save') ,content=save)),
    collapse='\n<br>\n',section_tags='')

#do.call('render_skeleton', args) %>% HTML()


#combine all args
#------------------
multi_args<-list(
  list(title=NULL ,
       description=NULL,
       args=args_main),
  list(title=submodule_title('Kruskall-Wallis (two-class comparison of means)') ,
       description=KS_description,
       args=args_KS))

out<-lapply(1:length(multi_args),function(i){
  title<-multi_args[[i]]$title
  content<-do.call('render_skeleton', multi_args[[i]]$args) 
  c(title,multi_args[[i]]$description,content)
}) %>% 
  unlist() %>%
  paste0(.,collapse = '\n<br>\n') 

out %>% HTML()

```
